package Game_2;
public class Creating_Questions {
    /*This methods add al questions and answer in a list of other class*/
    public Creating_Questions() {
        ButtonPane.list.add("¿Java es un lenguaje orientado a objetos?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("¿Java fue el primer lenguaje de programacion de alto nivel?");
        ButtonPane.list.add(false);
        ButtonPane.list.add("¿int, char, float, string, boolean son tipos de datos?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("¿if, else, for y while son estructuras de control?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("universidad = 'UTN';\n¿Es correcta esta declaracion?");
        ButtonPane.list.add(false);
        ButtonPane.list.add("¿Java fue creado por Sun Microsystems?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("¿Java fue creado en 1996?");
        ButtonPane.list.add(false);
        ButtonPane.list.add("¿Un char en java ocupa 8 bits?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("public static void()\n\t System.out.println('Esta bien escrito este metodo');\n¿Esta bien escrito el metodo?");
        ButtonPane.list.add(false);
        ButtonPane.list.add("int num = 25.0\n¿Esto es correcto?");
        ButtonPane.list.add(false);
        ButtonPane.list.add("int i = 0;\nwhile(i < 10){\n\tSystem.out.println('Esta bien escrito la estructura de control');\n}\n¿La estructura de control esta bien escrita?");
        ButtonPane.list.add(false);
        ButtonPane.list.add("break;\n¿Se usa para detener el programa?");
        ButtonPane.list.add(false);
        ButtonPane.list.add("/* */\n¿Los anteriores signos son usados para hacer un comentario largo en java y que no sea visible en la ejecucion?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("System.out.println('Hola');\n¿Esta bien escrito el print?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("public, private, protected\n¿Lo anterior son modificadores de acceso?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("¿Si declaro una variable 'final' puede cambiar su valor durante la ejecucion del programa?");
        ButtonPane.list.add(false);
        ButtonPane.list.add("ArrayList list = new ArrayList<>();\n¿La declaracion es correcta?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("<,>,==,||,&&\n¿Los signos anteriores en java son estructuras de control?");
        ButtonPane.list.add(false);
        ButtonPane.list.add("boolean num = true,num_1 = false;\nif((num == true) && !(num_1 == true)){\n}\n\t¿La condicion se cumple?\n");
        ButtonPane.list.add(true);
        ButtonPane.list.add("String s = 'esto es un String';\n¿Es correcta esta declaracion?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("class Myclass extends JPanel{\n}\n¿Esta bien escrita la herencia?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("public class Myclass extends JPanel{\n\tpublic Myclass(){\n\t}\n}\n¿Esta bien escrito el constructor?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("¿Puedo usar una variable de una clase a otra clase de diferente paquete sin la declarar 'public' la variable?");
        ButtonPane.list.add(false);
        ButtonPane.list.add("¿El creador del lenguaje java fue James Gosling?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("int num1= 25;\nint num2=50;\nSystem.out.println(!(num1 > num2));\n¿Que valor booleano retorna el print?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("¿Las listas son lo mismo que un arreglo?");
        ButtonPane.list.add(false);
        ButtonPane.list.add("¿Un String es lo mismo que un Char?");
        ButtonPane.list.add(false);
        ButtonPane.list.add("'Una clase es un modelo que nos permite inicializar objetos'\n ¿Verdadero o falso?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("¿La palabra 'Swing' en Java hace referencia al cambio de valores?");
        ButtonPane.list.add(false);
        ButtonPane.list.add("For, while, do/while\n ¿Se consideran bucles?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("¿Las clases deben llevar su nombre en miniscula?");
        ButtonPane.list.add(false);
        ButtonPane.list.add("La clase Scanner se utiliza para obtener datos por medio de la consola\n¿Verdadero o Falso?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("String[][] matriz = new [2][2]\n¿La declaración es correcta?");
        ButtonPane.list.add(false);
        ButtonPane.list.add("If/else, switch\n¿Son sentencias de salto?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("A<B\nSegún la sentencia anterior ¿A es mayor que B?");
        ButtonPane.list.add(false);
        ButtonPane.list.add("La sintaxis de Java deriva de C y C++\n¿Verdadero o Falso?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("¿Los operadores boleanos hacen referencia a datos númericos?");
        ButtonPane.list.add(false);
        ButtonPane.list.add("Las operaciones de lectura y escritura pertenecen a java.net\n¿Verdadero o Falso?");
        ButtonPane.list.add(false);
        ButtonPane.list.add("¿NetBeans es un entorno de desarrollo libre?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("¿Los operadores lógicos permiten establecer relaciones entre dos valores?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("Java no cuenta con gran cantidad de librerias para trabajar\n¿Verdadero o Falso?");
        ButtonPane.list.add(false);
        ButtonPane.list.add("¿IDE es multiplataforma?");
        ButtonPane.list.add(true);
        ButtonPane.list.add("Los atributos representan un conjunto de objetos con un comportamientos\nregido por variables\n¿Verdadero o False?");
        ButtonPane.list.add(false);
    }
}
